apiVersion: 1

datasources:
  - name: Course Transfer DB
    type: postgres
    access: proxy
    url: localhost:5432
    database: course_transfer
    user: grafana_readonly
    secureJsonData:
      password: 'GrafanaReadOnly2025!'  # Change this!
    jsonData:
      sslmode: 'prefer'
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1400
    editable: false
    isDefault: true
