"""Add constraint violation tracking to PlanCourse

Revision ID: f54a517d7e8f
Revises: 
Create Date: 2025-11-17 11:44:07.242804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54a517d7e8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('constraint_violation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('constraint_violation_reason', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_plan_courses_constraint_violation'), ['constraint_violation'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_courses_constraint_violation'))
        batch_op.drop_column('constraint_violation_reason')
        batch_op.drop_column('constraint_violation')

    # ### end Alembic commands ###
