"""Add otp_secret to advisor_auth for TOTP authentication

Revision ID: f93f0333ad95
Revises: 0400c4e9198b
Create Date: 2025-11-25 16:39:43.116256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93f0333ad95'
down_revision = '0400c4e9198b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor_auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=32), nullable=True))

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_plans_advisor_email_advisor_auth'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'advisor_auth', ['advisor_email'], ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_plans_advisor_email_advisor_auth'), 'advisor_auth', ['advisor_email'], ['email'], ondelete='SET NULL')

    with op.batch_alter_table('advisor_auth', schema=None) as batch_op:
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
